GET http://localhost:3001/api/category

###
GET http://localhost:3001/api


###
POST https://webhooks.mongodb-realm.com/api/client/v2.0/app/pangcu-srexp/service/PangcuAPI/incoming_webhook/api?secret=glock18.19mm HTTP/2
content-type: application/json

{
    "id":["bribZNKFb_N","asdfdasfas", "bribZNKFb_N", "asdfas"]
}